# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['src/dooservice_agent/__main__.py'],
    pathex=[],
    binaries=[],
    datas=[
        (
            'src/dooservice_agent/templates',
            'dooservice_agent/templates',
        ),
    ],
    hiddenimports=[
        # ── Agent ────────────────────────────────────────────────────────
        'dooservice_agent',
        'dooservice_agent.config',
        'dooservice_agent.cli',
        'dooservice_agent.cli.context',
        'dooservice_agent.cli.errors',
        'dooservice_agent.cli.output',
        'dooservice_agent.cli.commands',
        'dooservice_agent.cli.commands.bootstrap',
        'dooservice_agent.cli.commands.pg',
        'dooservice_agent.cli.commands.pgdog',
        'dooservice_agent.cli.commands.proxy',
        'dooservice_agent.cli.commands.serve',
        'dooservice_agent.cli.commands.systemd',
        'dooservice_agent.daemon',
        'dooservice_agent.daemon.serve',
        'dooservice_agent.daemon.scheduler',
        # ── SDK ──────────────────────────────────────────────────────────
        'dooservice_sdk',
        'dooservice_sdk.config',
        'dooservice_sdk.errors',
        'dooservice_sdk.sdk',
        'dooservice_sdk.backup',
        'dooservice_sdk.backup.service',
        'dooservice_sdk.bootstrap',
        'dooservice_sdk.bootstrap.bootstrap',
        'dooservice_sdk.bootstrap.pgdog',
        'dooservice_sdk.bootstrap.postgres',
        'dooservice_sdk.bootstrap.traefik',
        'dooservice_sdk.bootstrap.service_status',
        'dooservice_sdk.domains',
        'dooservice_sdk.domains.service',
        'dooservice_sdk.environments',
        'dooservice_sdk.environments.service',
        'dooservice_sdk.environments.odoo',
        'dooservice_sdk.environments.odoo_conf',
        'dooservice_sdk.git',
        'dooservice_sdk.git.service',
        'dooservice_sdk.git.addons',
        'dooservice_sdk.jobs',
        'dooservice_sdk.jobs.context',
        'dooservice_sdk.jobs.dispatcher',
        'dooservice_sdk.jobs.errors',
        'dooservice_sdk.jobs.registry',
        'dooservice_sdk.jobs.scheduler',
        'dooservice_sdk.jobs.handlers',
        'dooservice_sdk.jobs.handlers.backup',
        'dooservice_sdk.jobs.handlers.deployment',
        'dooservice_sdk.jobs.handlers.domain',
        'dooservice_sdk.jobs.handlers.env',
        'dooservice_sdk.jobs.handlers.git',
        'dooservice_sdk.jobs.handlers.logs',
        'dooservice_sdk.jobs.handlers.project',
        'dooservice_sdk.projects',
        'dooservice_sdk.projects.service',
        'dooservice_sdk.proxy',
        'dooservice_sdk.proxy.service',
        'dooservice_sdk.proxy.labels',
        'dooservice_sdk.proxy.traefik',
        # ── Transport (NATS) ─────────────────────────────────────────────
        'dooservice_transport',
        'dooservice_transport.agent',
        'dooservice_transport.errors',
        'dooservice_transport.subjects',
        'dooservice_transport.orchestrator',
        'dooservice_transport.protocol',
        'dooservice_transport.protocol.messages',
        # ── Protocol (job arg structs) ───────────────────────────────────
        'dooservice_protocol',
        # ── Supporting packages ──────────────────────────────────────────
        'dooservice_models',
        'dooservice_docker',
        'dooservice_dns',
        'dooservice_dns.cloudflare',
        'dooservice_dns.manager',
        'dooservice_dns.noop',
        'dooservice_dns.resolver',
        'dooservice_db_agent',
        'dooservice_db_agent.models',
        'dooservice_db_agent.repositories',
        'dooservice_s3',
        # ── CLI ──────────────────────────────────────────────────────────
        'cyclopts',
        'rich',
        'rich.console',
        'rich.table',
        'rich.text',
        'rich.markup',
        # ── NATS ─────────────────────────────────────────────────────────
        'nats',
        'nats.aio',
        'nats.aio.client',
        'nats.js',
        'nats.js.client',
        # ── APScheduler ──────────────────────────────────────────────────
        'apscheduler',
        'apscheduler.schedulers',
        'apscheduler.schedulers.asyncio',
        'apscheduler.triggers',
        'apscheduler.triggers.cron',
        'apscheduler.triggers.interval',
        'apscheduler.triggers.date',
        'apscheduler.executors',
        'apscheduler.executors.asyncio',
        'apscheduler.jobstores',
        'apscheduler.jobstores.memory',
        # ── Serialization ────────────────────────────────────────────────
        'msgspec',
        'msgspec.json',
        'msgspec.structs',
        # ── Logging ──────────────────────────────────────────────────────
        'structlog',
        'structlog.dev',
        'structlog.processors',
        'structlog.contextvars',
        # ── Docker SDK ───────────────────────────────────────────────────
        'docker',
        'docker.api',
        'docker.api.client',
        'docker.client',
        'docker.constants',
        'docker.errors',
        'docker.models',
        'docker.models.containers',
        'docker.models.images',
        'docker.models.networks',
        'docker.models.volumes',
        'docker.transport',
        'docker.transport.unixconn',
        'requests',
        'requests.adapters',
        'urllib3',
        'urllib3.connection',
        'urllib3.connectionpool',
        # ── ORM + SQLite ─────────────────────────────────────────────────
        'tortoise',
        'tortoise.backends',
        'tortoise.backends.sqlite',
        'tortoise.backends.sqlite.client',
        'tortoise.backends.sqlite.executor',
        'tortoise.contrib',
        'aiosqlite',
        'aiosqlite.core',
        # ── DNS ──────────────────────────────────────────────────────────
        'dns',
        'dns.asyncresolver',
        'dns.resolver',
        'dns.rdatatype',
        'dns.name',
        'dns.rdtypes',
        'dns.rdtypes.ANY',
        'dns.rdtypes.IN',
        # ── HTTP (Cloudflare DNS) ─────────────────────────────────────────
        'httpx',
        'httpx._transports',
        'httpx._transports.default',
        'httpcore',
        'h11',
        'anyio',
        'anyio._backends',
        'anyio._backends._asyncio',
        'sniffio',
        'certifi',
        'idna',
        # ── S3 ───────────────────────────────────────────────────────────
        'boto3',
        'boto3.s3',
        'boto3.s3.transfer',
        'botocore',
        'botocore.config',
        'botocore.exceptions',
        'botocore.auth',
        'botocore.credentials',
        'botocore.endpoint',
        'botocore.regions',
        'botocore.signers',
        'botocore.loaders',
        'jmespath',
        # ── System ───────────────────────────────────────────────────────
        'psutil',
        'dotenv',
        'tomlkit',
        # ── Git ──────────────────────────────────────────────────────────
        'pygit2',
        'pygit2.enums',
        'pygit2.options',
        'pygit2.errors',
        'pygit2.ffi',
        # ── CFFI backend (required by pygit2) ────────────────────────────
        '_cffi_backend',
        'cffi',
        'cffi.api',
        'cffi.backend_ctypes',
        # ── Stdlib async ─────────────────────────────────────────────────
        'asyncio',
        'sqlite3',
        'zoneinfo',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['pytest', 'unittest', 'tkinter', 'matplotlib', 'numpy'],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='dooservice-agent',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
